### ISSUE TITLE
Redirect Strategy Development

### ISSUE THREAD

**Issue by patphongs** [18F/fec-proxy#13]
**Proxy Redirect strategy:**
old.fec.gov (does not exist) --> www.fec.gov
liger.fec.gov (Does not resolve) --> transition.fec.gov

Exact match vs directory tree definitions need to be defined in nginx include file.

**Comment by patphongs** [comment]
Initial implementation in this PR #14

**Comment by LindsayYoung** [comment]
Closing this- thanks to all of @patphongs hard work
