### ISSUE TITLE
Sign requests to proxied apps

### ISSUE THREAD

**Issue by jmcarp** [18F/fec-proxy#3]
To restrict access to the proxied apps, sign proxied requests, e.g. using HMAC-SHA1. This functionality is available in the `set_misc` module, but not in nginx core:

```
set_hmac_sha1 $signature $secret_key $string_to_sign;
proxy_set_header x-signature $signature;
```

To implement, we could build nginx with the `set_misc` module under cflinuxfs2, upload the result to S3 (or someplace else), and update `manifest.yml` in the buildpack. Pinging @mbland @dlapiduz @ozzyjohnson @dhcole for guidance in the hope that you all have better ideas.

**Comment by dhcole** [comment]
Not sure... may we set up an 18F fork the static buildpack to reference a build of nginx with `set_misc`?

**Comment by mbland** [comment]
@jmcarp I presume this is the source of the module: https://github.com/openresty/set-misc-nginx-module

It looks like it'd work, given a `$string_to_sign` value that incorporates nginx builtin vars like `$request_body`, etc.

**Comment by dhcole** [comment]
More specifically, we could try a fork that reads the nginx url from the `Staticfile` first, then defaults to the buildback. This would allow users of the buildpack to compile whatever they need. We could even support a local path so the archive could be included in the repo. It's only 2.5mb for the basic build.

**Comment by jmcarp** [comment]
@mbland: right, I expect that it would work--it's just a question of getting it running on cloud foundry, given that we have to recompile nginx from source to include non-core modules.

@dhcole: :+1: to a configurable nginx url. I can take a crack at modifying the buildpack tonight. Looks like the "cflinuxfs2" stack is built on trusty, so I'll try building nginx with `set_misc` in a trusty vm and see what happens.
