### ISSUE TITLE
Investigate networking errors

### ISSUE THREAD

**Issue by LindsayYoung** [18F/fec-proxy#43]
Seeing too many Network unreachable errors with static assets in the logs.

**Comment by ccostino** [comment]
I took a quick look at the logs this morning to see what's going on, but what's weird is the errors being thrown don't match my experience on the site.  All static images appear fine and are returned with `200` status codes when I profile network connections.

In the logs, I'm seeing errors connecting to some of the resources, e.g.:

* seal.png
* headshot--walther.png
* headshot--no-photo.png
* headshot--goodman.png
* fec-table-tint.png
* feature--reporting.png
* headshot--hunter.png
* feature--data.png
* headshot--weintraub.png
* headshot--petersen.png
* wordmark.svg
* seal--inverse.svg
* feature--data.png
* us_flag_small.png
* feature--legal.png

And several others.  I did notice a couple of similar errors for requests made to the web app:

* /data/candidates/?cycle=2018&election_year=2018&office=H&state=KS&district=03

So it's not always static assets, just most of the time.  Here are a few other things I noticed, though:

* The errors all stem from trying to connect to an IPv6 address and that failing.  The address is by and large the same for all of the failed requests except for the last group within it, which alternates between two different sets from the section of the logs I looked at.
* After the errors (of which is usually two failed connect attempts), a regular request to CloudFront seems to go through just fine and is returned.
* The actual error is always the same:  `Network is unreachable`

I can't share specific log details here, so we can catch up offline to investigate further and see what's going on.

**Comment by LindsayYoung** [comment]
Those network unreachable errors are not showing up in the logs after we pushed the fix for #48. I will close this issue we can add further discussion in that thread.
