### ISSUE TITLE
Postmortem outages Jul 1 & 2 

### ISSUE THREAD

**Issue by LindsayYoung** [18F/fec-proxy#48]
## Overview
There was a high volume of 500 errors for pages and assets on fec.gov June 30 at 11 pm. We narrowed down the problem to the proxy app.

We had been experiencing intermittent connection errors. They were prevalent in the logs, so we had [looked into this before](https://github.com/18F/fec-proxy/issues/43). We had a hard time reproducing this error and did notice some patterns in the `Network is unreachable`as noted in the issue.

A new class of error cropped up on Friday June 30 at 11pm with the error message `socket() failed (97: Address family not supported by protocol) while connecting to upstream, client` This caused a high volume of noticeable errors on production and was present in the other environments as well. 

Asked for assistance in cg-support and @jmcarp suggested adding `ipv6=off` to the`resolver` in the proxy code. This was successfully tested out on dev and staging, before @patphongs deployed the code to production.

### Other remediations we tried 
We double checked the apps were not the problem before pursuing the issue with cloud.gov.

We tried:
- Re-staged cms and proxy
- Re-deployed cms
- Re-deployed proxy
- Reduced instance of the proxy to one and redeployed the proxy app 

## Identifying causes and remediations

- [x] schedule postmortem meeting on Monday (maybe as a team and with cloud.gov)

### Notes on the process
Learned some things about the logs:

Also noting that the logs truncate to the most recent 500 results, and if you request a different sort order, so you are looking at oldest and ask for the request agin, you still just get the most recent 500 results. You really have to hone in using the absolute time feature.

# Thanks
Thank you to @jmcarp @konklone @jcscottiii @patphongs @rjayasekera @PaulClark2 @jwchumley for working through this and getting the issue resolved.

**Comment by konklone** [comment]
> Also noting that the logs truncate to the most recent 500 results, and if you request a different sort order, so you are looking at oldest and ask for the request agin, you still just get the most recent 500 results. You really have to hone in using the absolute time feature.

I updated the [Advanced Settings](https://logs.fr.cloud.gov/app/kibana#/management/kibana/settings?_g=()) to bump the `discover:sampleSize` to 5000, which makes some queries take longer but lets the user page through more results. I am not sure whether updating the settings updated it for just me, or for all users.

**Comment by LindsayYoung** [comment]
postmortem doc 
https://docs.google.com/document/d/1bYmMTbbE8-d7l6z3lmNVRRxtBmUriCkHbJVr6ilDaaA/edit#
