### ISSUE TITLE
Updating efiling redirect

### ISSUE THREAD

**Issue by llienfec** [18F/fec-proxy#49]
It looks like the www.fec.gov/efiling redirect is sending users to an out-of-date efiling page.  For now, the redirect should go to: https://www.fec.gov/help-candidates-and-committees/filing-reports/electronic-filing/

In a few sprints when we work on organizing the pages in Wagtail, the address may change.  We'll let you know when that happens.  Thanks!

**Comment by llienfec** [comment]
Oops, intended to tag @patphongs  We may need a rush on this due to the filing deadlines this month.  Thanks!

**Comment by patphongs** [comment]
Ok will do! I will deploy the update tonight
