### ISSUE TITLE
Redirect for CommitteeDetailFilings

### ISSUE THREAD

**Issue by patphongs** [18F/fec-proxy#54]
There are 404 errors for Committee Filing details. We need to redirect to the appropriate filings tab on the new site. 

Example:
http://www.fec.gov/fecviewer/CommitteeDetailFilings.do?tabIndex=3&candidateCommitteeId=C00327239&electionYr=2010

Redirect to

https://www.fec.gov/data/committee/C00327239/?tab=filings

**Comment by AmyKort** [comment]
closing in favor of https://github.com/18F/openFEC-web-app/issues/2254
