### ISSUE TITLE
Handle redirects for classic.fec.gov and ftp.fec.gov

### ISSUE THREAD

**Issue by patphongs** [18F/fec-proxy#56]
We need to redirect classic.fec.gov and ftp.fec.gov using Gashaw's redirect server with Apache.

**Completion Criteria:**
- [ ] Double check classic redirect rules to change appropriately with classic.fec.gov is decommissioned. Ask about fecletter.
- [ ] Create rule to redirect classic.fec.gov --> www.fec.gov
- [ ] ftp.fec.gov redirect to /files/bulk-downloads/index.html in s3 bucket

**Comment by patphongs** [comment]
These are the classic redirect rules that we need to update before the shutdown: [spreadsheet](https://docs.google.com/spreadsheets/d/1y6HiGeOAfeMWyPIzHqRoyYqYjVRBiYlxNNEm5gJ87Dc/edit#gid=0).

**Comment by gmengistu** [comment]
Ok will do but we decided not to redirect classic, correct? It will disappear when Waltham gets shutdown.

**Comment by patphongs** [comment]
@gmengistu Yes we will want to do redirects for classic too. This will provide better user experience and these search applications are heavily used. There are 16 links that are heavily used on classic and will still be available and live for people to use. I will email you the PDF of links that are the most visited.

**Comment by AmyKort** [comment]
Is this issue still relevant?

**Comment by gmengistu** [comment]
I would think no - since we are going to bring up the site at DC3, no redirects are needed.
