### ISSUE TITLE
Redirect meetings/hearings pages

### ISSUE THREAD

**Issue by patphongs** [18F/fec-proxy#59]
Meetings and hearings pages will be moved from https://www.fec.gov/updates/?update_type=meetings to https://www.fec.gov/meetings/. We need to add redirects to accommodate. We also need to redirect individual meetings pages that will be moving from `/updates/` to `/meetings/`

**Comment by AmyKort** [comment]
Is this complete along with https://github.com/18F/fec-cms/issues/1138 ?
